flush ruleset

##### INCLUDE DATA #####
# ToDo: should name specific files for safety

include "/etc/fwPi/data/*.conf"

##### DEFINITIONS #####

define WAN_IF = "eth0"
define LAN_IF = "wlan0"

table inet filter {

##### MODULE CHAINS #####

##### BASIC CHAINS #####

    chain forward {

            type filter hook forward priority 0;
            policy drop;

            ct state established,related accept

            # allow DNS queries to Pi-hole
            iif $LAN_IF udp dport 53 accept
            iif $LAN_IF tcp dport 53 accept

            # other allowed ports
            iif "$LAN_IF" oif "eth0" tcp dport @allow_tcp_ports accept
            iif "$LAN_IF" oif "eth0" udp dport @allow_udp_ports accept

            # networklayer
            ip saddr @deny_ipv4 drop
            ip6 saddr @deny_ipv6 drop
        }

    chain input {

        type filter hook input priority 0;
        policy drop;

        ct state established,related accept
        iif lo accept

        accept
    }

    chain output {

        type filter hook output priority 0;
        policy accept;

    }

}

##### NAT TABLE #####
table ip nat {

    chain prerouting {
            type nat hook prerouting priority 0;

            # redirect DNS (UDP & TCP port 53) to Pi-hole
            iif "$LAN_IF" tcp dport 53 dnat to 192.168.1.2:53
            iif "$LAN_IF" udp dport 53 dnat to 192.168.1.2:53

            # Redirect HTTPS to HAProxy
            iif "$LAN_IF" tcp dport 443 redirect to :8443
    }

    chain postrouting {
        type nat hook postrouting priority 100;

        # Masquerade traffic leaving via eth0
        oif "eth0" masquerade
    }

}
