flush ruleset

# ToDo: should name specific files for safety
include "/etc/fwPi/data/*.conf"

define WAN_IF = "eth0"
define LAN_IF = "wlan0"

define PIHOLE_IP4 = 192.168.8.201
#define PIHOLE_IP6 = #todoo

table inet filter {

    chain input {
        type filter hook input priority filter
        policy drop

        ct state vmap { established:accept, related:accept, invalid:drop }

        iif lo accept

        ip protocol icmp accept
        # ip protocol icmp icmp type { echo-request, echo-reply, destination-unreachable, time-exceeded } accept
        #ip6 nexthdr icmpv6 accept

        # DHCP (LAN) request and reply
        iif $LAN_IF udp sport 67 udp dport 68 accept

        # DNS (Pi-hole)
        iif $LAN_IF ip daddr $PIHOLE_IP4 udp dport 53 accept
        iif $LAN_IF ip daddr $PIHOLE_IP4 tcp dport 53 accept
        #iif $LAN_IF ip6 daddr $PIHOLE_IP6 udp dport 53 accept
        #iif $LAN_IF ip6 daddr $PIHOLE_IP6 tcp dport 53 accept

        # SSH (LAN only)
        iif $LAN_IF tcp dport 22 accept

        # HAProxy frontend !!todo
        iif $LAN_IF tcp dport { 80, 443, 8443 } accept

        limit rate 5/second log prefix "DROP_INPUT: " drop
    }

    chain output {
        type filter hook output priority 0;
        policy drop

        ct state vmap { established:accept, related:accept, invalid:drop }

        oif lo accept

        # DNS (router → upstream)
        oif $WAN_IF udp dport 53 accept
        oif $WAN_IF tcp dport 53 accept

        # Web (updates etc.)
        oif $WAN_IF tcp dport { 80, 443 } accept

        # NTP
        oif $WAN_IF udp dport 123 accept

        # ssh pulls
        oif $WAN_IF tcp dport 22 accept

        # ICMP
        oif $WAN_IF ip protocol icmp accept
        #oif $WAN_IF ip6 nexthdr icmpv6 accept

        limit rate 5/second log prefix "DROP_OUTPUT: " drop
    }

    chain forward {
        type filter hook forward priority 0;
        policy drop;

        ct state vmap { established:accept, related:accept, invalid:drop }

        # Allow DNS ONLY to Pi-hole
        iif $LAN_IF ip daddr $PIHOLE_IP4 udp dport 53 accept
        iif $LAN_IF ip daddr $PIHOLE_IP4 tcp dport 53 accept
        #iif $LAN_IF ip6 daddr $PIHOLE_IP6 udp dport 53 accept
        #iif $LAN_IF ip6 daddr $PIHOLE_IP6 tcp dport 53 accept

        # Block all other DNS attempts
        iif $LAN_IF udp dport 53 drop
        iif $LAN_IF tcp dport 53 drop
        #iif $LAN_IF meta nfproto ipv6 udp dport 53 drop
        #iif $LAN_IF meta nfproto ipv6 tcp dport 53 drop

        # Block DoT
        iif $LAN_IF tcp dport 853 drop
        #iif $LAN_IF meta nfproto ipv6 tcp dport 853 drop

        # Blcok Quic
        iif $LAN_IF udp dport 443 drop
        #iif $LAN_IF meta nfproto ipv6 udp dport 443 drop

        # General internet access
        iif $LAN_IF oif $WAN_IF accept

        # Local service: allow LAn client to HAProxy
        iif $LAN_IF tcp dport 8443 accept

        # Allow ICMPv6
        #ip6 nexthdr icmpv6 accept

        limit rate 5/second log prefix "DROP_FORWARD: " drop
    }
}

table ip nat {

    chain prerouting {
        type nat hook prerouting priority -100;

        # DNS -> Pi-hole
        iif $LAN_IF udp dport 53 dnat to $PIHOLE_IP4:53
        iif $LAN_IF tcp dport 53 dnat to $PIHOLE_IP4:53

        # HTTP(S) -> HAProxy
        iif $LAN_IF tcp dport 443 redirect to :8443
        iif $LAN_IF tcp dport 80 redirect to :8443
    }

    chain postrouting {
        type nat hook postrouting priority 100;

        # Masquerade traffic leaving via eth0
        oif $WAN_IF masquerade
    }
}
