flush ruleset

##### INCLUDE DATA #####
# ToDo: should name specific files for safety

include "/etc/fwPi/data/*.conf"

##### DEFINITIONS #####

define HTTP_PORT = 80
define HTTPS_PORT = 443
define DNS_PORT = 53
define DOT_PORT = 853

define WAN_IF = "eth0"
define LAN_IF = "wlan0"

table inet filter {

##### MODULE CHAINS #####

    chain network_layer {

            ip saddr @deny_ipv4 drop

        }

##### BASIC CHAINS #####

    chain forward {

            type filter hook forward priority 0;
            policy drop;

            # pipeline
            jump network_layer

            accept
        }

    chain input {

        type filter hook input priority 0;
        policy drop;

        ct state established,related accept
        iif lo accept

        accept
    }

    chain output {

        type filter hook output priority 0;
        policy accept;

    }

}

##### NAT TABLE #####
table ip nat {
    chain postrouting {
        type nat hook postrouting priority 100;

        # Masquerade traffic leaving via eth0
        oif "eth0" masquerade
    }
}
