#!/usr/bin/env bash
#
# Testing throughput with iperf3

# CONFIG
LOG=$"/Users/johannapauler/Desktop/fwPi/tests/results/iperf3_base.txt"

run_throughput(){
  read -rp "Start server: ``$ iperf3 -s``, then press Enter..."
  # This selects portnumber automatically. Can i a static one instead?
  local modes=(
    "base"
    "td"
    "tc"
  )

  for mode in "${modes[@]}"; do
      echo
      echo " Testing mode: $mode"
      read -rp "Set fw-censor to '$mode', then press Enter..."

      echo "------ $mode ------" >> $LOG
      iperf3 -c 192.168.50.1 -p 5201 -t 30 --logfile $LOG

      echo "Finished: $mode"
  done
}