#!/bin/bash

# /usr/local/bin/fwPiCLI/config

# -----------------------------------------------------------
# configuration
# -----------------------------------------------------------
# shellcheck disable=SC2034
# darf man so?
NFT_BASE="/etc/nftables.conf"
NFT_TD="/usr/local/lib/fwPi/config/nftables/traffic_drop.nft"
NFT_TC="/usr/local/lib/fwPi/config/nftables/traffic_control.nft"

TABLE="inet filter"
CHAIN_FWD="forward"
CHAIN_TD="traffic_drop"
CHAIN_TC="traffic_control"
JUMP_COMMENT_TD="td-jump"
JUMP_COMMENT_TC="tc-jump"

IFACE="wlan0"
STATUS_FILE="/run/fw-censor.mode"

# default throttle rates — override via argument
TC_RATE="${2:-128kbit}"
TC_CEIL="256kbit"
TC_LATENCY="500ms"
TOTAL_RATE="100mbit"
