table inet filter {

    chain forward {

            type filter hook forward priority 0;
            policy drop;

            # pipeline
            jump network_layer

            accept
        }

    chain input {

        type filter hook input priority 0;
        policy drop;

        ct state established,related accept
        iif lo accept

        accept
    }

    chain output {

        type filter hook output priority 0;
        policy accept;

    }

}