#!/usr/bin/env bash

# ============================================================
# Configuration
# ============================================================

# shellcheck disable=SC2034
FWPI_REPO="$(pwd)"
FWPI_DIR="/usr/local/lib/fwPi"

NFT_CONFIG="$FWPI_DIR/config/nftables/nftables.conf"
NFT_TARGET="/etc/nftables.conf"
NFT_BACKUP="/etc/nftables.conf.fwPi.backup"

FWCLI="$FWPI_DIR/fwPiCLI"

# WAN interface
WAN_IF="eth0"
# WAN_IPV4="128.130.39.108" and WAN_IPV6="2a06:d1c1:ef::2"
WAN_IPV4=$(ip -4 -br addr show "$WAN_IF" | awk '{print $3}' | cut -d/ -f1)
WAN_IPV6=$(ip -6 -br addr show "$WAN_IF" | awk '{print $3}' | cut -d/ -f1)

# LAN/AP interface
LAN_IF="wlan0"
# LAN_IPV4="192.168.50.1/24" and LAN_IPV6="2a06:d1c1:ee:1::1"
LAN_IPV4=$(ip -4 -br addr show "$LAN_IF" | awk '{print $3}')
LAN_IPV4=$(ip -6 -br addr show "$LAN_IF" | awk '{print $3}')

AP_NAME="fwAccessPoint"
AP_PASSWORD="password"

PIHOLE_LIST="file:///usr/local/lib/fwPi/config/pihole/my_blocklist.txt"
