flush ruleset

# helpers → tables → data → chains → modules

# helper definitions
include "/etc/fwPi/nftables/helpers/definitions.conf"

# tables
include "/etc/fwPi/nftables/tables/inet_filter_table.conf"

# data (sets/maps)
include "/etc/fwPi/nftables/data/*.conf"

# feature modules
include "/etc/fwPi/nftables/modules/*.conf"

