flush ruleset

# helpers → tables → data → chains → modules

# helper definitions
include "/etc/nftables/helpers/*.conf"

# tables
include "/etc/nftables/tables/*.conf"

# data (sets/maps)
include "/etc/nftables/data/*.conf"

# base chains
include "/etc/nftables/chains/*.conf"

# feature modules
include "/etc/nftables/modules/*.conf"

